name: build-push
on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: e1himself/goss-installation-action@v1.1.0
        with:
          version: "v0.3.16"
        name: Install goss/dgoss
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: radicale:latest
      - name: Test
        env:
          # radicale needs a little more then 0.2 seconds to start up
          GOSS_SLEEP: 1
        run: dgoss run -ti -v ${PWD}/tests/test-passwd-file:/radicale/passwd-file radicale
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "ghcr.io/moritzheiber/radicale"
